### ISSUE TITLE
ChunkedEcondingError

### ISSUE THREAD

**Issue by beachc15** [beachc15/Option-Data-Downloader-for-Rasp-Pi#2]
About 5% of data is lost each day from this ChunkedEncodingError. I am not used to dealing with this kind of error so I am placing this in the official "issues" section to show how I work through it. I have listed all text from the error message below.

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 360, in _error_catcher
    yield
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 669, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 624, in _handle_chunk
    returned_chunk = self._fp._safe_read(self.chunk_left)
  File "/usr/lib/python3.7/http/client.py", line 622, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(3385 bytes read, 711 more expected)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 490, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 694, in read_chunked
    self._original_response.close()
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 378, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(3385 bytes read, 711 more expected)', IncompleteRead(3385 bytes read, 711 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/python_projects/python_prod/rasbpi_options/get_options.py", line 187, in <module>
    run_program()
  File "/home/pi/python_projects/python_prod/rasbpi_options/get_options.py", line 148, in run_program
    inp = main()
  File "/home/pi/python_projects/python_prod/rasbpi_options/get_options.py", line 39, in main
    expiration_list = this_yf_object.options
  File "/usr/local/lib/python3.7/dist-packages/yfinance/ticker.py", line 195, in options
    self._download_options()
  File "/usr/local/lib/python3.7/dist-packages/yfinance/ticker.py", line 56, in _download_options
    r = _requests.get(url=url, proxies=proxy).json()
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 686, in send
    r.content
  File "/usr/lib/python3/dist-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/lib/python3/dist-packages/requests/models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(3385 bytes read, 711 more expected)', IncompleteRead(3385 bytes read, 711 more expected))
```

My goal is to stop losing this data everyday.

**Comment by beachc15** [comment]
I Will reopen if I still run into errors. Unable to test at this point.

**Comment by beachc15** [comment]
Also, I wish I could have done a more detailed fix to this. There has to be some alternative where I store the partial data and then get the rest instead of throwing everything out and restarting. This may be something that I do if I ever end up scraping it myself.
