### ISSUE TITLE
update_price_funcs.py getting ValueError for time match

### ISSUE THREAD

**Issue by beachc15** [beachc15/Option-Data-Downloader-for-Rasp-Pi#3]
when attempting to match time, update_price_funcs.py throws a ValueError for every file it tries to look through. Unsure of why just yet. Currently, 0% of files are being correctly updated.

`/home/pi/Documents/data/options_daily/12_03_20/12_03_20-17:35.csv
Traceback (most recent call last):
  File "update_price_funcs.py", line 219, in <module>
    main()
  File "update_price_funcs.py", line 210, in main
    alter_csv(df_prices, file_str)
  File "update_price_funcs.py", line 196, in alter_csv
    df['pctPriceDiff'] = df.apply(lambda x: price_delta_in_pct(x['strike'], x['currentPriceDay']), axis=1)
  File "/home/pi/python_projects/python_prod/rasbpi_options/env/lib/python3.8/site-packages/pandas/core/frame.py", line 7552, in apply
    return op.get_result()
  File "/home/pi/python_projects/python_prod/rasbpi_options/env/lib/python3.8/site-packages/pandas/core/apply.py", line 180, in get_result
    return self.apply_standard()
  File "/home/pi/python_projects/python_prod/rasbpi_options/env/lib/python3.8/site-packages/pandas/core/apply.py", line 271, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/home/pi/python_projects/python_prod/rasbpi_options/env/lib/python3.8/site-packages/pandas/core/apply.py", line 300, in apply_series_generator
    results[i] = self.f(v)
  File "update_price_funcs.py", line 196, in <lambda>
    df['pctPriceDiff'] = df.apply(lambda x: price_delta_in_pct(x['strike'], x['currentPriceDay']), axis=1)
  File "update_price_funcs.py", line 151, in price_delta_in_pct
    pct_change = (round((strike - current_price) / current_price), round_int)
ValueError: cannot convert float NaN to integer`

**Comment by beachc15** [comment]
Its because of the terrible time I have debugging lambda functions. It was passing in BRKB when its called BRK-B in the lookup from YFinance. Potentially fix with just an "if" statement for now, or rename the BRKB column to BRK-B  with a "clean" type function.

**Comment by beachc15** [comment]
Turns out, its not pulling a current price for BRKB and its not throwing an error until it tried to use "current price" 
![image](https://user-images.githubusercontent.com/60740158/101269020-699fc100-372f-11eb-846d-4aa6a0ac4993.png)
attachment is the "current price" column of the dataframe pulled locally.

Need to fix issue inside of "current price" get function

**Comment by beachc15** [comment]
In all seriousness. Closed as I added a very basic way to fix this problem. The error comes from the get_options puller which saves berkshire hathaway-B as BRKB. Tomorrow I will fix the get_option file.
